name:                plotex
version:             0.1.0.0
github:              "githubuser/plotex"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/plotex#readme>

dependencies:
- base >= 4.7 && < 5
- HaTeX == 3.18.0.0
- inline-r == 0.9.1
- mtl == 2.2.2
- random == 1.1
- directory == 1.3.*
- Chart == 1.8.3
- Chart-cairo == 1.8.3
- text == 1.2.3.0
- optparse-applicative == 0.14.2.0

library:
  source-dirs: src

executables:
  plotex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotex

tests:
  plotex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plotex
